### PR TITLE
adds option to disable ipv6

### PR DESCRIPTION
**Pull request by marxmanEUW**

### CODE REVIEW

**Comment by marxmanEUW** [comment]
Sorry, i picked the wrong section.

**Comment by wookietreiber** [comment]
Thanks again!

**Comment by wookietreiber** [comment]
The patch shipped with version 0.4.0 to galaxy.

**Comment by marxmanEUW** [comment]
I still have a problem:
I use `postfix_aliases`, so the role will run `newaliases`. But since I disabled IPv6 on my server and the default value for `inet_protcols` is `all` the command will fail. So I have to alter the value manually for the very first run to `ipv4` to get this role finish successfully.

Is it possible to move the configration and restart/reload tasks of the `main.cf` file above the `alias` tasks?

**Comment by wookietreiber** [comment]
@marxmanEUW Please open a separate issue for that.

**Pull request merged**
